// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "MCPProxy Support",
            "url": "https://github.com/smart-mcp-proxy/mcpproxy-go"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/diagnostics": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Get comprehensive health diagnostics including upstream errors, OAuth requirements, missing secrets, and Docker status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "diagnostics"
                ],
                "summary": "Get health diagnostics",
                "responses": {
                    "200": {
                        "description": "Health diagnostics",
                        "schema": {
                            "$ref": "#/definitions/contracts.Diagnostics"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/docker/status": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Retrieve current Docker availability and recovery status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "docker"
                ],
                "summary": "Get Docker status",
                "responses": {
                    "200": {
                        "description": "Docker status information",
                        "schema": {
                            "$ref": "#/definitions/contracts.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/doctor": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": [],
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Aggregates health information from all servers, checks OAuth status, missing secrets, and Docker availability",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "diagnostics"
                ],
                "summary": "Run health diagnostics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "apikey",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Comprehensive health diagnostics",
                        "schema": {
                            "$ref": "#/definitions/main.Diagnostics"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/index/search": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Search across all upstream MCP server tools using BM25 keyword search",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tools"
                ],
                "summary": "Search for tools",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "type": "integer",
                        "default": 10,
                        "description": "Maximum number of results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Search results",
                        "schema": {
                            "$ref": "#/definitions/contracts.SearchToolsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request (missing query parameter)",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Get essential server metadata including version, web UI URL, and endpoint addresses\nThis endpoint is designed for tray-core communication",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Get server information",
                "responses": {
                    "200": {
                        "description": "Server information",
                        "schema": {
                            "$ref": "#/definitions/contracts.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/servers": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": [],
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Returns all configured MCP servers with connection status, tool counts, and aggregate statistics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "servers"
                ],
                "summary": "List all upstream servers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key (alternative to header for browser/SSE)",
                        "name": "apikey",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of servers with statistics",
                        "schema": {
                            "$ref": "#/definitions/main.ServersResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/servers/disable_all": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Disable all configured upstream MCP servers with partial failure handling",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "servers"
                ],
                "summary": "Disable all servers",
                "responses": {
                    "200": {
                        "description": "Bulk disable results with success/failure counts",
                        "schema": {
                            "$ref": "#/definitions/management.BulkOperationResult"
                        }
                    },
                    "403": {
                        "description": "Forbidden (management disabled)",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/servers/enable_all": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Enable all configured upstream MCP servers with partial failure handling",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "servers"
                ],
                "summary": "Enable all servers",
                "responses": {
                    "200": {
                        "description": "Bulk enable results with success/failure counts",
                        "schema": {
                            "$ref": "#/definitions/management.BulkOperationResult"
                        }
                    },
                    "403": {
                        "description": "Forbidden (management disabled)",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/servers/reconnect": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Force reconnection to all upstream MCP servers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "servers"
                ],
                "summary": "Reconnect all servers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Reason for reconnection",
                        "name": "reason",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "All servers reconnected successfully",
                        "schema": {
                            "$ref": "#/definitions/contracts.ServerActionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/servers/restart_all": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": [],
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Sequentially restarts all configured servers. Returns partial success if some servers fail.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "servers"
                ],
                "summary": "Restart all upstream servers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "apikey",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Restart results with success/failure counts",
                        "schema": {
                            "$ref": "#/definitions/main.RestartAllResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - read-only mode",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/servers/{id}/disable": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Disable a specific upstream MCP server",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "servers"
                ],
                "summary": "Disable an upstream server",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Server disabled successfully",
                        "schema": {
                            "$ref": "#/definitions/contracts.ServerActionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Server not found",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/servers/{id}/enable": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Enable a specific upstream MCP server",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "servers"
                ],
                "summary": "Enable an upstream server",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Server enabled successfully",
                        "schema": {
                            "$ref": "#/definitions/contracts.ServerActionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Server not found",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/servers/{id}/login": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Initiate OAuth authentication flow for a specific upstream MCP server. Use force=true to force re-authentication even if tokens exist.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "servers"
                ],
                "summary": "Trigger OAuth login for server",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Force OAuth flow even if tokens exist (default: false)",
                        "name": "force",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OAuth login initiated successfully",
                        "schema": {
                            "$ref": "#/definitions/contracts.ServerActionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request (missing server ID)",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Server not found",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/servers/{id}/logs": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Retrieve log entries for a specific upstream MCP server",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "servers"
                ],
                "summary": "Get server logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Number of log lines to retrieve",
                        "name": "tail",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Server logs retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/contracts.GetServerLogsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request (missing server ID)",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Server not found",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/servers/{id}/quarantine": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Place a specific upstream MCP server in quarantine to prevent tool execution",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "servers"
                ],
                "summary": "Quarantine a server",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Server quarantined successfully",
                        "schema": {
                            "$ref": "#/definitions/contracts.ServerActionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request (missing server ID)",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Server not found",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/servers/{id}/restart": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Restart the connection to a specific upstream MCP server",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "servers"
                ],
                "summary": "Restart an upstream server",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Server restarted successfully",
                        "schema": {
                            "$ref": "#/definitions/contracts.ServerActionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Server not found",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/servers/{id}/tools": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Retrieve all available tools for a specific upstream MCP server",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "servers"
                ],
                "summary": "Get tools for a server",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Server tools retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/contracts.GetServerToolsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request (missing server ID)",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Server not found",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/servers/{id}/unquarantine": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Remove a specific upstream MCP server from quarantine to allow tool execution",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "servers"
                ],
                "summary": "Unquarantine a server",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Server unquarantined successfully",
                        "schema": {
                            "$ref": "#/definitions/contracts.ServerActionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request (missing server ID)",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Server not found",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/servers/{name}/logs": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": [],
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Returns recent log entries for a specific upstream server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "servers"
                ],
                "summary": "Get server logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of lines to return (default 50, max 1000)",
                        "name": "tail",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "apikey",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Log entries",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.LogEntry"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid tail parameter",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Server not found",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/servers/{name}/restart": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": [],
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Stops and restarts the connection to a specific upstream MCP server. Emits servers.changed event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "servers"
                ],
                "summary": "Restart an upstream server",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API Key (alternative to header)",
                        "name": "apikey",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid server name",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - read-only mode or management disabled",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Server not found",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats/tokens": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Retrieve token savings statistics across all servers and sessions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get token savings statistics",
                "responses": {
                    "200": {
                        "description": "Token statistics",
                        "schema": {
                            "$ref": "#/definitions/contracts.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Get comprehensive server status including running state, listen address, upstream statistics, and timestamp",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Get server status",
                "responses": {
                    "200": {
                        "description": "Server status information",
                        "schema": {
                            "$ref": "#/definitions/contracts.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tools/call": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "ApiKeyQuery": []
                    }
                ],
                "description": "Execute a tool on an upstream MCP server (wrapper around MCP tool calls)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tools"
                ],
                "summary": "Call a tool",
                "parameters": [
                    {
                        "description": "Tool call request with tool name and arguments",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "arguments": {
                                    "type": "object"
                                },
                                "tool_name": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tool call result",
                        "schema": {
                            "$ref": "#/definitions/contracts.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request (invalid payload or missing tool name)",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error or tool execution failure",
                        "schema": {
                            "$ref": "#/definitions/contracts.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "contracts.Diagnostics": {
            "type": "object",
            "properties": {
                "docker_status": {
                    "$ref": "#/definitions/contracts.DockerStatus"
                },
                "missing_secrets": {
                    "description": "Renamed to avoid conflict",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contracts.MissingSecretInfo"
                    }
                },
                "oauth_issues": {
                    "description": "OAuth parameter mismatches",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contracts.OAuthIssue"
                    }
                },
                "oauth_required": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contracts.OAuthRequirement"
                    }
                },
                "runtime_warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "timestamp": {
                    "type": "string"
                },
                "total_issues": {
                    "type": "integer"
                },
                "upstream_errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contracts.UpstreamError"
                    }
                }
            }
        },
        "contracts.DockerStatus": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "boolean"
                },
                "error": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "contracts.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "contracts.GetServerLogsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contracts.LogEntry"
                    }
                },
                "server_name": {
                    "type": "string"
                }
            }
        },
        "contracts.GetServerToolsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "server_name": {
                    "type": "string"
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contracts.Tool"
                    }
                }
            }
        },
        "contracts.GetServersResponse": {
            "type": "object",
            "properties": {
                "servers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contracts.Server"
                    }
                },
                "stats": {
                    "$ref": "#/definitions/contracts.ServerStats"
                }
            }
        },
        "contracts.IsolationConfig": {
            "type": "object",
            "properties": {
                "cpu_limit": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "image": {
                    "type": "string"
                },
                "memory_limit": {
                    "type": "string"
                },
                "timeout": {
                    "type": "string"
                },
                "working_dir": {
                    "type": "string"
                }
            }
        },
        "contracts.LogEntry": {
            "type": "object",
            "properties": {
                "fields": {
                    "type": "object",
                    "additionalProperties": true
                },
                "level": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "server": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "contracts.MissingSecretInfo": {
            "type": "object",
            "properties": {
                "secret_name": {
                    "type": "string"
                },
                "used_by": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "contracts.OAuthConfig": {
            "type": "object",
            "properties": {
                "auth_url": {
                    "type": "string"
                },
                "client_id": {
                    "type": "string"
                },
                "extra_params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "pkce_enabled": {
                    "type": "boolean"
                },
                "redirect_port": {
                    "type": "integer"
                },
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token_expires_at": {
                    "description": "When the OAuth token expires",
                    "type": "string"
                },
                "token_url": {
                    "type": "string"
                },
                "token_valid": {
                    "description": "Whether token is currently valid",
                    "type": "boolean"
                }
            }
        },
        "contracts.OAuthIssue": {
            "type": "object",
            "properties": {
                "documentation_url": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "issue": {
                    "type": "string"
                },
                "missing_params": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "resolution": {
                    "type": "string"
                },
                "server_name": {
                    "type": "string"
                }
            }
        },
        "contracts.OAuthRequirement": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "server_name": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "contracts.SearchResult": {
            "type": "object",
            "properties": {
                "matches": {
                    "type": "integer"
                },
                "score": {
                    "type": "number"
                },
                "snippet": {
                    "type": "string"
                },
                "tool": {
                    "$ref": "#/definitions/contracts.Tool"
                }
            }
        },
        "contracts.SearchToolsResponse": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/contracts.SearchResult"
                    }
                },
                "took": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "contracts.Server": {
            "type": "object",
            "properties": {
                "args": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "authenticated": {
                    "description": "OAuth authentication status",
                    "type": "boolean"
                },
                "command": {
                    "type": "string"
                },
                "connected": {
                    "type": "boolean"
                },
                "connected_at": {
                    "type": "string"
                },
                "connecting": {
                    "type": "boolean"
                },
                "created": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "env": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "isolation": {
                    "$ref": "#/definitions/contracts.IsolationConfig"
                },
                "last_error": {
                    "type": "string"
                },
                "last_reconnect_at": {
                    "type": "string"
                },
                "last_retry_time": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "oauth": {
                    "$ref": "#/definitions/contracts.OAuthConfig"
                },
                "oauth_status": {
                    "description": "OAuth status: \"authenticated\", \"expired\", \"error\", \"none\"",
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "quarantined": {
                    "type": "boolean"
                },
                "reconnect_count": {
                    "type": "integer"
                },
                "retry_count": {
                    "type": "integer"
                },
                "should_retry": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "token_expires_at": {
                    "description": "When the OAuth token expires (ISO 8601)",
                    "type": "string"
                },
                "tool_count": {
                    "type": "integer"
                },
                "tool_list_token_size": {
                    "description": "Token size for this server's tools",
                    "type": "integer"
                },
                "updated": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "user_logged_out": {
                    "description": "True if user explicitly logged out (prevents auto-reconnection)",
                    "type": "boolean"
                },
                "working_dir": {
                    "type": "string"
                }
            }
        },
        "contracts.ServerActionResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "async": {
                    "type": "boolean"
                },
                "server": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "contracts.ServerStats": {
            "type": "object",
            "properties": {
                "connected_servers": {
                    "type": "integer"
                },
                "docker_containers": {
                    "type": "integer"
                },
                "quarantined_servers": {
                    "type": "integer"
                },
                "token_metrics": {
                    "$ref": "#/definitions/contracts.ServerTokenMetrics"
                },
                "total_servers": {
                    "type": "integer"
                },
                "total_tools": {
                    "type": "integer"
                }
            }
        },
        "contracts.ServerTokenMetrics": {
            "type": "object",
            "properties": {
                "average_query_result_size": {
                    "description": "Typical retrieve_tools output (tokens)",
                    "type": "integer"
                },
                "per_server_tool_list_sizes": {
                    "description": "Token size per server",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "saved_tokens": {
                    "description": "Difference",
                    "type": "integer"
                },
                "saved_tokens_percentage": {
                    "description": "Percentage saved",
                    "type": "number"
                },
                "total_server_tool_list_size": {
                    "description": "All upstream tools combined (tokens)",
                    "type": "integer"
                }
            }
        },
        "contracts.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "success": {
                    "type": "boolean"
                }
            }
        },
        "contracts.Tool": {
            "type": "object",
            "properties": {
                "annotations": {
                    "$ref": "#/definitions/contracts.ToolAnnotation"
                },
                "description": {
                    "type": "string"
                },
                "last_used": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "schema": {
                    "type": "object",
                    "additionalProperties": true
                },
                "server_name": {
                    "type": "string"
                },
                "usage": {
                    "type": "integer"
                }
            }
        },
        "contracts.ToolAnnotation": {
            "type": "object",
            "properties": {
                "destructiveHint": {
                    "type": "boolean"
                },
                "idempotentHint": {
                    "type": "boolean"
                },
                "openWorldHint": {
                    "type": "boolean"
                },
                "readOnlyHint": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "contracts.UpstreamError": {
            "type": "object",
            "properties": {
                "error_message": {
                    "type": "string"
                },
                "server_name": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "main.Diagnostics": {
            "type": "object",
            "properties": {
                "docker_status": {
                    "$ref": "#/definitions/main.DockerStatus"
                },
                "missing_secrets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.MissingSecret"
                    }
                },
                "oauth_required": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.OAuthRequirement"
                    }
                },
                "runtime_warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "timestamp": {
                    "type": "string",
                    "example": "2025-11-23T10:35:12Z"
                },
                "total_issues": {
                    "type": "integer",
                    "example": 3
                },
                "upstream_errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.UpstreamError"
                    }
                }
            }
        },
        "main.DockerStatus": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "boolean",
                    "example": true
                },
                "error": {
                    "type": "string",
                    "example": ""
                },
                "version": {
                    "type": "string",
                    "example": "24.0.7"
                }
            }
        },
        "main.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "MGMT_DISABLED"
                },
                "details": {
                    "type": "string",
                    "example": "Set disable_management=false in config"
                },
                "error": {
                    "type": "string",
                    "example": "management operations disabled"
                }
            }
        },
        "main.LogEntry": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string",
                    "example": "INFO"
                },
                "message": {
                    "type": "string",
                    "example": "Tool call: create_issue"
                },
                "server": {
                    "type": "string",
                    "example": "github-server"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2025-11-23T10:30:00Z"
                }
            }
        },
        "main.MissingSecret": {
            "type": "object",
            "properties": {
                "secret_name": {
                    "type": "string",
                    "example": "GITHUB_TOKEN"
                },
                "used_by": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"github-server\"",
                        "\"gh-issues\"]"
                    ]
                }
            }
        },
        "main.OAuthRequirement": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string",
                    "example": "2025-11-22T18:00:00Z"
                },
                "message": {
                    "type": "string",
                    "example": "Run: mcpproxy auth login --server=github-server"
                },
                "server_name": {
                    "type": "string",
                    "example": "github-server"
                },
                "state": {
                    "type": "string",
                    "example": "expired"
                }
            }
        },
        "main.RestartAllResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"server-1: connection timeout\"]"
                    ]
                },
                "failed_count": {
                    "type": "integer",
                    "example": 1
                },
                "success_count": {
                    "type": "integer",
                    "example": 9
                }
            }
        },
        "main.Server": {
            "type": "object",
            "properties": {
                "connected": {
                    "type": "boolean",
                    "example": true
                },
                "enabled": {
                    "type": "boolean",
                    "example": true
                },
                "error": {
                    "type": "string",
                    "example": ""
                },
                "name": {
                    "type": "string",
                    "example": "github-server"
                },
                "quarantined": {
                    "type": "boolean",
                    "example": false
                },
                "tool_count": {
                    "type": "integer",
                    "example": 25
                }
            }
        },
        "main.ServerStats": {
            "type": "object",
            "properties": {
                "connected": {
                    "type": "integer",
                    "example": 7
                },
                "disabled": {
                    "type": "integer",
                    "example": 2
                },
                "enabled": {
                    "type": "integer",
                    "example": 8
                },
                "errors": {
                    "type": "integer",
                    "example": 1
                },
                "quarantined": {
                    "type": "integer",
                    "example": 1
                },
                "total": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "main.ServersResponse": {
            "type": "object",
            "properties": {
                "servers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Server"
                    }
                },
                "stats": {
                    "$ref": "#/definitions/main.ServerStats"
                }
            }
        },
        "main.UpstreamError": {
            "type": "object",
            "properties": {
                "error_message": {
                    "type": "string",
                    "example": "connection refused"
                },
                "server_name": {
                    "type": "string",
                    "example": "weather-api"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2025-11-23T09:15:30Z"
                }
            }
        },
        "management.BulkOperationResult": {
            "type": "object",
            "properties": {
                "errors": {
                    "description": "Map of server name to error message",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "failed": {
                    "description": "Number of failed operations",
                    "type": "integer"
                },
                "successful": {
                    "description": "Number of successful operations",
                    "type": "integer"
                },
                "total": {
                    "description": "Total servers processed",
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API key authentication. Provide your API key in the X-API-Key header.",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        },
        "ApiKeyQuery": {
            "description": "API key authentication via query parameter. Use ?apikey=your-key",
            "type": "apiKey",
            "name": "apikey",
            "in": "query"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "MCPProxy API",
	Description:      "MCPProxy REST API for managing MCP servers, tools, and diagnostics\n\nMCPProxy is a smart proxy for AI agents using the Model Context Protocol (MCP).\nIt provides intelligent tool discovery, massive token savings, and built-in security quarantine.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
